[tool.poetry]
name = "subtitles_translator"
version = "0.0.1"
description = "Automatic subtitles translation with a local neural machine translation model. No third-party service required: the translation is done locally with small but efficient neural network models."
authors = ["TDHM <tdhm-git@outlook.com>"]
repository = "https://github.com/tdhm/subtitles-translator"
documentation = "https://tdhm.github.io/subtitles-translator/"
readme = "README.md"
packages = [
  {include = "subtitles_translator"}
]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
transformers = "^4.27.2"
sentencepiece = "^0.1.97"
torch = "2.0.0"
fastapi = "^0.101.0"
uvicorn = {extras = ["standard"], version = "^0.23.2"}

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.22.0"
pandas = "^1.5.3"
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
mypy = "^0.981"
pre-commit = "^2.20.0"
tox = "^3.25.1"
ruff = "^0.0.260"
google-cloud-storage = "^2.10.0"
gcsfs = "^2023.6.0"
pydantic = "^2.1.1"
requests = "^2.31.0"

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.4.2"
mkdocs-material = "^8.5.10"
mkdocstrings = {extras = ["python"], version = "^0.19.0"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
subtitles_translator = 'subtitles_translator.cli:translate_subtitles_cli'

[tool.black]
line-length = 120
target-version = ['py37']
preview = true

[tool.mypy]
files = ["subtitles_translator"]
disallow_untyped_defs = "True"
disallow_any_unimported = "True"
no_implicit_optional = "True"
check_untyped_defs = "True"
warn_return_any = "True"
warn_unused_ignores = "True"
show_error_codes = "True"

[tool.ruff]
target-version = "py37"
line-length = 120
fix = true
select = [
    # flake8-2020
    "YTT",
    # flake8-bandit
    "S",
    # flake8-bugbear
    "B",
    # flake8-builtins
    "A",
    # flake8-comprehensions
    "C4",
    # flake8-debugger
    "T10",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # mccabe
    "C90",
    # pycodestyle
    "E", "W",
    # pyflakes
    "F",
    # pygrep-hooks
    "PGH",
    # pyupgrade
    "UP",
    # ruff
    "RUF",
    # tryceratops
    "TRY",
]
ignore = [
    # LineTooLong
    "E501",
    # DoNotAssignLambda
    "E731",
]

[tool.ruff.per-file-ignores]
"tests/*" = ["S101"]

[tool.coverage.report]
skip_empty = true

[tool.coverage.run]
branch = true
source = ["subtitles_translator"]


